### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Downlosc** [idemia/python-wsq#3]
Hi this is not really an issue. I just wanted to ask you if this library can be used to compress images to wsq and uncompress. In that case, how?

**Comment by olivier-heurtier-ingroupe** [comment]
Hi @Downlosc 

Sorry for my (very) late answer.
Yes you can use it to compress and uncompress grayscale images (mode 'L' in Pillow) using the usual Pillow API. You just have to import the module wsq and the format becomes available as any other Pillow-supported format.
You can see first samples in the README and refer to Pillow documentation for more advanced examples.

**Comment by olivier-heurtier-ingroupe** [comment]
See example added in README
